trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
#- task: AzureResourceGroupDeployment@2
#  inputs:
#    azureSubscription: 'myconnection0'
#    action: 'Create Or Update Resource Group' # Options: create Or Update Resource Group, select Resource Group, start, stop, stopWithDeallocate, restart, delete, deleteRG
#    resourceGroupName: $(resourceGroupName)
#    location: 'westeurope'# Required when action == Create Or Update Resource Group
#    templateLocation: 'Linked artifact' # Options: linked Artifact, uRL Of The File
    #csmFileLink: # Required when templateLocation == URL Of The File
    #csmParametersFileLink: # Optional
#    csmFile: '$(Build.SourcesDirectory)/**/azureDeploy.json' # Required when  TemplateLocation == Linked Artifact
    #csmParametersFile: # Optional
    #overrideParameters: # Optional
#    deploymentMode: 'Incremental' # Options: Incremental, Complete, Validate
    #enableDeploymentPrerequisites: 'None' # Optional. Options: none, configureVMwithWinRM, configureVMWithDGAgent
    #teamServicesConnection: # Required when enableDeploymentPrerequisites == ConfigureVMWithDGAgent
    #teamProject: # Required when enableDeploymentPrerequisites == ConfigureVMWithDGAgent
    #deploymentGroupName: # Required when enableDeploymentPrerequisites == ConfigureVMWithDGAgent
    #copyAzureVMTags: true # Optional
    #runAgentServiceAsUser: # Optional
    #userName: # Required when enableDeploymentPrerequisites == ConfigureVMWithDGAgent && RunAgentServiceAsUser == True
    #password: # Optional
    #outputVariable: # Optional
    #deploymentName: # Optional
    #deploymentOutputs: # Optional
    #addSpnToEnvironment: false # Optional

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'myconnection0'
    subscriptionId: '2e39dc9c-a38f-475c-aa16-dfb68153287b'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'prueba123'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/Azure/azure-quickstart-templates/blob/master/application-workloads/mongo/mongodb-on-centos/azuredeploy.json'
    csmParametersFileLink: 'https://github.com/Azure/azure-quickstart-templates/blob/master/application-workloads/mongo/mongodb-on-centos/azuredeploy.parameters.json'
    deploymentMode: 'Incremental'

  condition: always()
  continueOnError: true
