trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    ConnectedServiceName: 'myconnection0'
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resourceGroupName)
    location: 'North Europe'
    deploymentMode: 'Incremental'
    csmFile: $(cmsFile)
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--output $(Build.ArtifactStagingDirectory)'
