trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: azcli_resourcegroup_create
    steps:
          - task: AzureCLI@2
            displayName: 'Deploy Resource Group'
            inputs:
              azureSubscription: 'myconnection2'
              scriptType: bash
              scriptLocation: inlineScript
              addSpnToEnvironment: true
              inlineScript: |
                #!/bin/bash
                az group create -l westeurope -n mydemorg
