trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'myconnection'
    subscriptionId: '2e39dc9c-a38f-475c-aa16-dfb68153287b'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'prueba123'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/jlopezpa/ResourceGroupTest/main/StorageAccount/linkedStorageAccount.json?token=AWLMDJKGDEWKLTQP6GMU57DBRLXOW'
    overrideParameters: '-projectName PipelineDev'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployTemplateTest'
  #condition: always()
  continueOnError: true
