trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
-     task: AzureResourceGroupDeployment@2
  inputs:
    deploymentScope: 'Resource Group'
    ConnectedServiceName: 'myconnection0'
    subscriptionId: '2e39dc9c-a38f-475c-aa16-dfb68153287b'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'KensTestRG'
    location: 'North Europe'
    templateLocation: 'Linked artifact'
    csmFile: '**/azuredeploy.json'
    deploymentMode: 'Incremental'
